### PR TITLE
Create Newton_Raphson.py

### PR DESCRIPTION
**Pull request by PatilSwarali**
This program is an example of how to solve a physics problem using computation. We use Newton Raphson method to find the root of the equation of motion of a rocket and numerically determine the time t taken by the rocket to reach the speed of sound (340 m/s)

### CODE REVIEW

**Review by dipeshdigwal — APPROVED** [review]
nice work @Swarali-glitch .

**Comment by PatilSwarali** [comment]
Thanks a lot! Can I contribute more to this?

**Comment by dipeshdigwal** [comment]
yeah sure you are more than invited for the same. 
suggestion : please look up at commenting code

**Comment by PatilSwarali** [comment]
Sure sure, I would do that.

**Pull request merged**
