### PR TITLE
Create SimpsonMethod.py

### PR DESCRIPTION
**Pull request by PatilSwarali**
This program numerically evaluates an error function using the Simposon's method for calculating integrals. The output gives the value of the error function for 10 decimal places.

### CODE REVIEW

**Review by dipeshdigwal — COMMENTED** [review]
have you checked for output of this file? if no please check the output on certain testcases and please provide testcases in the documentation.

**Comment by PatilSwarali** [comment]
Yes, I have checked the output. The function to be integrated is defined in the program itself and the interval over which it is integrated is also given.

**Comment by dipeshdigwal** [comment]
i was asking for testcase in mathematical form as displayed in https://g.co/kgs/AxvWnN and not in functional form as defined in your function. This would be helpful to create a nice documentation for newcomers. this time its fine, I am merging the file but please take care of these small issues.
also please add this file to folder integration first

**Comment by PatilSwarali** [comment]
Oh, I see. Sure, I will try to make the changes that you have suggested.

**Pull request merged**
